import { Footer, Navbar } from '@/components';
import './globals.css';
import { Inter } from 'next/font/google';
import {CrowdFundingProvider} from '../context/CrowdFunding';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CrowdFundingProvider>
          <Navbar />
          {children}
          <Footer />
        </CrowdFundingProvider>
      </body>
    </html>
  )
}
